steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['-v']
  - name: 'node'
    entrypoint: 'node'
    args: ['-v']
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'buildGCP']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'
